package modelo.coreJuego.fichas;

public enum Rasgos {
    BREAKER, BULKY, DARK, DISRUPTOR, DRAGON, ELECTRIC, FAIRY, FIRE, FLYING, GHOST, GRASS, GROUND, HAZARD,
    ICE, NORMAL, NULL ,PIVOT, POISON, PSYCHIC, REVENGER, ROCK, STEEL, SUPPORT, SWEEPER, UTILITY, WALL, WATER, BUG;

}
